services:
  - type: web
    name: fly-me-away
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    secrets:
      - name: STREAMLIT_SECRETS
        mountPath: /.streamlit/secrets.toml