[search]
origin = "Zürich Airport (ZRH), Zurich, Switzerland"
destination = "Francisco de Sá Carneiro Airport (OPO), Porto, Portugal"
departure_day = "friday"
number_of_nights = 2
direct_flight = true
travel_class = "ECONOMY"
departure_time_option = "Any"
return_time_option = "Any"
